#!/usr/bin/python3
import sys
import time
import RPi.GPIO as GPIO
import sys
import http.client as http
import urllib
import json

deviceId = "D0HIR3qf"
deviceKey = "h0pvWq5S0FPMy0Ng"

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(17,GPIO.OUT)

def post_to_mcs(payload):
        headers = {"deviceKey": deviceKey}
        not_connected = 1
        while (not_connected):
                try:
                        conn = http.HTTPConnection("api.mediatek.com:80")
                        conn.connect()
                        not_connected = 0
                except (http.HTTPException, socket.error) as ex:
                        print ("Error: %s" % ex)
                        time.sleep(10)
                         # sleep 10 seconds
        conn.request("GET", "/mcs/v2/devices/" + deviceId + "/datachannels/con/datapoints",json.dumps(payload), headers)
        response = conn.getresponse()
        print( response.status, response.reason, json.dumps(payload), time.strftime("%c"))
        data = response.read()
        s = json.loads(data)
        a = s["dataChannels"]
        b = a[0]["dataPoints"][0]["values"]["value"]
        GPIO.output(17,b)
        conn.close()

while(True):
        payload = {}
        post_to_mcs(payload)
        time.sleep(1)
